name: Daily Keeper Doc Monitor

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write  # 💥 Needed to allow git push

jobs:
  run-spider:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}  # 💥 This authorizes the push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scrapy html2text

      - name: Run Scrapy spider
        run: scrapy crawl keeper_docs

      - name: Commit and push changes
        run: |
          git config user.name "keeper-doc-bot"
          git config user.email "bot@users.noreply.github.com"
          git add output/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated scrape update: $(date -u)"
            git push
          fi

      - name: Format diff and URL list
        id: format_diff
        run: |
          echo "## Changed URLs" > report.txt
          git diff --name-only HEAD~1 HEAD | sed -e 's/output/https:\/\/docs.keeper.io\/en\/keeperpam/g ; s/\.md$//g' >> report.txt
          echo "## Diff Summary" >> report.txt
          git show --no-color >> report.txt

      - name: Retrieve secrets from Keeper
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |-
            4rtq8BnDYPvqa2eDOtxbCg/field/login > LOGIN
            4rtq8BnDYPvqa2eDOtxbCg/field/password > PASSWORD
            4rtq8BnDYPvqa2eDOtxbCg/field/recipients > RECIPIENT

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ steps.ksecrets.outputs.LOGIN }}
          password: ${{ steps.ksecrets.outputs.PASSWORD }}
          subject: Keeper PAM Documentation Update
          to: ${{ steps.ksecrets.outputs.RECIPIENT }}
          from: GitHub Bot <tlaycock@keepersecurity.com>
          content_type: text/plain
          body: file://report.txt
